// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	TimeLimit     int32                  `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit   int32                  `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuLimit      int32                  `protobuf:"varint,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorRequest) Reset() {
	*x = ExecutorRequest{}
	mi := &file_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorRequest) ProtoMessage() {}

func (x *ExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorRequest.ProtoReflect.Descriptor instead.
func (*ExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecutorRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecutorRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutorRequest) GetTimeLimit() int32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *ExecutorRequest) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ExecutorRequest) GetCpuLimit() int32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

type ExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExecutionTime int64                  `protobuf:"varint,2,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorResponse) Reset() {
	*x = ExecutorResponse{}
	mi := &file_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorResponse) ProtoMessage() {}

func (x *ExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorResponse.ProtoReflect.Descriptor instead.
func (*ExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecutorResponse) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

var File_proto_executor_proto protoreflect.FileDescriptor

const file_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executor.proto\x12\bexecutor\"\xb6\x01\n" +
	"\x0fExecutorRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x04 \x01(\x05R\ttimeLimit\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x05R\vmemoryLimit\x12\x1b\n" +
	"\tcpu_limit\x18\x06 \x01(\x05R\bcpuLimit\"Q\n" +
	"\x10ExecutorResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12%\n" +
	"\x0eexecution_time\x18\x02 \x01(\x03R\rexecutionTime2U\n" +
	"\x0fExecutorService\x12B\n" +
	"\aExecute\x12\x19.executor.ExecutorRequest\x1a\x1a.executor.ExecutorResponse\"\x00B\x12Z\x10/internal/proto/b\x06proto3"

var (
	file_proto_executor_proto_rawDescOnce sync.Once
	file_proto_executor_proto_rawDescData []byte
)

func file_proto_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)))
	})
	return file_proto_executor_proto_rawDescData
}

var file_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_executor_proto_goTypes = []any{
	(*ExecutorRequest)(nil),  // 0: executor.ExecutorRequest
	(*ExecutorResponse)(nil), // 1: executor.ExecutorResponse
}
var file_proto_executor_proto_depIdxs = []int32{
	0, // 0: executor.ExecutorService.Execute:input_type -> executor.ExecutorRequest
	1, // 1: executor.ExecutorService.Execute:output_type -> executor.ExecutorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_executor_proto_init() }
func file_proto_executor_proto_init() {
	if File_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_proto_depIdxs,
		MessageInfos:      file_proto_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_proto = out.File
	file_proto_executor_proto_goTypes = nil
	file_proto_executor_proto_depIdxs = nil
}
