version: "3.9"

services:
  judge:
    build: .
    container_name: judge_service
    ports:
      - "8080:8080"
    networks:
      - judge_network

networks:
  default:
    driver: bridge
  judge_network:
    driver: bridge
